### ISSUE TITLE
Continuous repairing over the same square

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/rsmt2d#72]
### What
The current state of the lib does not take into account a use case where the user executes `RepairExtendedSqaure` multiple times over the same data square slice. In such case, rsmt2d [fills with zeroes](https://github.com/celestiaorg/rsmt2d/blob/master/extendeddatacrossword.go#L86-L92) all the nill shares/chunks that are hashed on the subsequent repair preventing [sanity check](https://github.com/celestiaorg/rsmt2d/blob/9c00b79df4d4c58cbae7f14309728ce8dde0ab80/extendeddatacrossword.go#L359) to pass.

### Why
This is useful for repairing retries as new data comes from the network without doing additional copies of the square.

### How
As per @adlerjohn, the original intent to fill nil shares/chunks with zeroes was to match the library interface of the underlying codec implementations. However, we have codec wrappers/facades for each codec implementation that should independently adapt to the library interface without forcing the higher-level abstracted rsmt2d logic to match low-level APIs. 

#### TODO
- [ ] Change `Codec` interface contract to always accept nil shares instead of zeroed shares
- [ ] Investigate codec implementation libraries and their API codec; Find the difference and define which are different from the contract above
- [ ] Update local `Codec` implementation facades to match the contract above by adapting it to the underlying libraries API.

**Comment by liamsi** [comment]
Decision:
 - use nils in RepairExtendedDataSquare and move the usage of zeroes to the specific codec impl when needed
 - this essentially makes the BitMask implementation and its usage obsolete
